//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cms_node_taxonomies_map")]
pub struct Model {
    pub bundle: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub nid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cms_nodes::Entity",
        from = "Column::Nid",
        to = "super::cms_nodes::Column::Nid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Node,
    #[sea_orm(
        belongs_to = "super::cms_taxonomies::Entity",
        from = "Column::Tid",
        to = "super::cms_taxonomies::Column::Tid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Taxonomy,
}

impl ActiveModelBehavior for ActiveModel {}
