//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cron_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub cron_id: String,
    pub lot_id: String,
    pub weight: i16,
    pub name: String,
    pub group: String,
    pub invoke_target: String,
    pub params: String,
    pub message: String,
    pub status: String,
    pub exception_info: String,
    pub is_once: String,
    pub created_at: DateTime,
    pub elapsed_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
