//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "crons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub vid: String,
    pub count: i32,
    pub run_count: i32,
    pub name: String,
    pub params: String,
    pub group: String,
    pub invoke_target: String,
    pub expression: String,
    pub misfire_policy: String,
    pub concurrent: String,
    pub status: String,
    pub remark: String,
    pub last_time: Option<DateTime>,
    pub next_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    pub created_by: i64,
    pub updated_by: i64,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
