//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub nid: i64,
    pub uuid: String,
    pub vid: String,
    pub bundle: String,
    pub title: String,
    pub viewed: i32,
    pub deleted: String,
    pub published_at: Option<DateTime>,
    pub created_by: i64,
    pub updated_by: i64,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::node_body::Entity")]
    NodeBody,
}

impl Related<super::node_body::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NodeBody.def()
    }
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        super::node_categories_map::Relation::Category.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::node_categories_map::Relation::Node.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<&str> for Column {
    fn from(name: &str) -> Self {
        match name {
            "created_at" => Column::CreatedAt,
            _ => Column::Nid,
        }
    }
}

