//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "operation_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub time_id: i64,
    pub title: String,
    pub business_type: String,
    pub method: String,
    pub request_method: String,
    pub operator_type: String,
    pub name: String,
    pub department_name: String,
    pub url: String,
    pub ip: String,
    pub location: String,
    #[sea_orm(column_type = "Text")]
    pub param: String,
    #[sea_orm(column_type = "Text")]
    pub path_param: String,
    #[sea_orm(column_type = "Text")]
    pub json_result: String,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub error_message: String,
    pub duration: i64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
