//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "short_links")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub link: String,
    pub name: String,
    pub description: String,
    pub viewed: i32,
    pub deleted: String,
    pub created_by: i64,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
