//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "sys_menus")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub pid: String,
    pub path: Option<String>,
    pub name: Option<String>,
    pub icon: Option<String>,
    pub r#type: Option<String>,
    pub query: Option<String>,
    pub weight: Option<i32>,
    pub api: Option<String>,
    pub status: Option<String>,
    pub method: Option<String>,
    pub component: Option<String>,
    pub visible: Option<String>,
    pub is_cache: Option<String>,
    pub log_method: Option<String>,
    pub data_cache_method: Option<String>,
    pub is_frame: Option<String>,
    pub data_scope: Option<String>,
    pub remark: Option<String>,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
