@base = http://localhost:5150

###

GET {{base}}/v1/info HTTP/1.1

###

# @name accessToken
# @prompt username 输入用户名
# @prompt password 输入密码
POST {{base}}/v1/auth/access-token HTTP/1.1
content-type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

@token = {{accessToken.response.body.data.token}}

### 

# @name menuTree
POST {{base}}/v1/menu/tree HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "vid": "backend"
}

### 

# @name authInfo
POST {{base}}/v1/auth/info HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### 

# @name fileUpload
POST {{base}}/v1/file/upload HTTP/1.1
Authorization: Bearer {{token}}
content-type: multipart/form-data; boundary=----RestClientFormBoundary

------RestClientFormBoundary
Content-Disposition: form-data; name="storage"

oss
------RestClientFormBoundary
Content-Disposition: form-data; name="type"

image/png
------RestClientFormBoundary
Content-Disposition: form-data; name="size"

64056
------RestClientFormBoundary
Content-Disposition: form-data; name="name"

triger.jpg
------RestClientFormBoundary
Content-Disposition: form-data; name="file"; filename="triger.jpg"
Content-Type: image/jpeg

< /Users/aqrun/Downloads/triger.jpg
------RestClientFormBoundary--