[workspace]
members = [
    "oicnp-api",
    "migration",
    "oicnp-derives",
    "oicnp-core",
    "oicnp-cmd",
    "oicnp-links",
    "frontend",
    "oicnp-zino",
]
exclude = ["oicnp-backend", "oicnp-frontend", "oicnp-yew", "docs"]
default-members = ["oicnp-api"]
