'use client'

import React, { useEffect, useState } from 'react';
import './globals.css'
import type { Metadata } from 'next'
import MainLayout from './MainLayout';
import UserLogin from '~/containers/UserLogin';
import { RecoilRoot } from 'recoil';
import { useAuthState } from '~/hooks';
import {
  SyncOutlined,
} from '@ant-design/icons';

const metadata: Metadata = {
  title: 'Create Next App111',
  description: 'Generated by create next app',
}

/**
 * main layout widget
 */
const LayoutWidget: React.FC<React.PropsWithChildren<{}>> = ({
  children,
}) => {
  const [auth] = useAuthState(true);
  const [initLoading, setInitLoading] = useState(true);

  useEffect(() => {
    setInitLoading(false);
  }, []);

  if (initLoading) {
    return (
      <div className="oicnp-loading-container">
        <SyncOutlined spin />
      </div>
    );
  }

  if (!auth?.user) {
    return (
      <UserLogin />
    );
  }

  return (
    <MainLayout>
      {children}
    </MainLayout>
  );
};

/**
 * main layout
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = false;

  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <LayoutWidget>{children}</LayoutWidget>
        </RecoilRoot>
      </body>
    </html>
  )
}
