'use client'

import React, { useEffect, useState } from 'react';
import './globals.css'
import type { Metadata } from 'next'
import { RecoilRoot } from 'recoil';
import {
  SyncOutlined,
} from '@ant-design/icons';
import UserLogin from '~/containers/UserLogin';
import { useAuthState } from '~/hooks';
import MainLayout from './main-layout';

// eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars -- metadata
const metadata: Metadata = {
  title: 'Create Next App111',
  description: 'Generated by create next app',
}

/**
 * main layout widget
 */
function LayoutWidget ({
  children,
}: React.PropsWithChildren): JSX.Element {
  const [auth] = useAuthState(true);
  const [initLoading, setInitLoading] = useState(true);

  useEffect(() => {
    setInitLoading(false);
  }, []);

  if (initLoading) {
    return (
      <div className="oicnp-loading-container">
        <SyncOutlined spin />
      </div>
    );
  }

  if (!auth.user) {
    return (
      <UserLogin />
    );
  }

  return (
    <MainLayout>
      {children}
    </MainLayout>
  );
}

/**
 * main layout
 */
export default function RootLayout ({
  children,
}: React.PropsWithChildren): JSX.Element {
  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <LayoutWidget>{children}</LayoutWidget>
        </RecoilRoot>
      </body>
    </html>
  );
}
