
export interface Mountain {
  id: number;
  name: string;
  high: number;
  province: string;
  city: string;
  county: string;
  times?: number;
  /** 难度等级 */
  level?: number;
  /** 景色指数 */
  scene?: number;
}

export const mountains: Mountain[] = [
  { id: 1, name: '太白山', high: 3767, province: '陕西省', city: '宝鸡市', county: '太白县', level: 5, scene: 5 },
  { id: 2,  name: '万仙阵', high: 3555, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 3,  name: '麦秸岭', high: 3520, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 4,  name: '九重石海', high: 3495, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 5,  name: '飞机梁', high: 3481, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 6,  name: '鳌山', high: 3476, province: '陕西省', city: '宝鸡市', county: '太白县', level: 5, scene: 5 },
  { id: 7,  name: '塔三', high: 3437, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 8,  name: '塔一', high: 3425, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 9,  name: '塔二', high: 3420, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 10,  name: '金字塔', high: 3418, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 11,  name: '梁一', high: 3401, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 12,  name: '顶棚梁', high: 3400, province: '陕西省', city: '宝鸡市', county: '太白县', level: 5, scene: 3 },
  { id: 13,  name: '梁三', high: 3303, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 14,  name: '梁二', high: 3238, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 15,  name: '骆驼峰', high: 3123, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 16,  name: '放羊寺', high: 3084, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 17,  name: '昏人坪梁', high: 3071, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 18,  name: '石庙子梁', high: 3052, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 19,  name: '鸭嘴山', high: 3050, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 20,  name: '冰晶顶', high: 3015, province: '陕西省', city: '西安市', county: '鄠邑区', level: 5, scene: 5 },
  { id: 21,  name: '西光头山', high: 2996, province: '陕西省', city: '西安市', county: '周至县', level: 4, scene: 4 },
  { id: 22,  name: '东梁', high: 2965, province: '陕西省', city: '安康市', county: '宁陕县', level: 5, scene: 4 },
  { id: 23,  name: '葱草坪', high: 2933, province: '陕西省', city: '汉中市', county: '洋县' },
  { id: 24,  name: '娘娘台', high: 2929, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 25,  name: '七女峰', high: 2912, province: '陕西省', city: '宝鸡市', county: '眉县' },
  { id: 26,  name: '草垭子', high: 2896, province: '陕西省', city: '安康市', county: '宁陕县', level: 4, scene: 4 },
  { id: 27,  name: '光头山', high: 2887, province: '陕西省', city: '西安市', county: '长安区', level: 4, scene: 4 },
  { id: 28,  name: '明星寺', high: 2860, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 29,  name: '天华山', high: 2850, province: '陕西省', city: '安康市', county: '宁陕县', level: 1, scene: 5 },
  { id: 30,  name: '一脚踏三县', high: 2823, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 31,  name: '玉皇山', high: 2819, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 32,  name: '牛背梁', high: 2802, province: '陕西省', city: '商洛市', county: '柞水县', level: 5, scene: 5 },
  { id: 33,  name: '新大坪梁', high: 2801, province: '陕西省', city: '西安市', county: '鄠邑区' },
  { id: 34,  name: '兵马营', high: 2759, province: '陕西省', city: '西安市', county: '鄠邑区' },
  { id: 35,  name: '锅坑梁', high: 2750, province: '陕西省', city: '宝鸡市', county: '凤县' },
  { id: 36,  name: '大坪梁', high: 2741, province: '陕西省', city: '西安市', county: '鄠邑区', level: 5, scene: 1 },
  { id: 37,  name: '透马驹', high: 2738, province: '陕西省', city: '宝鸡市', county: '凤县' },
  { id: 38,  name: '鹰嘴崖', high: 2730, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 39,  name: '首阳山', high: 2719, province: '陕西省', city: '西安市', county: '周至县', level: 5, scene: 1 },
  { id: 40,  name: '鹿角梁', high: 2701, province: '陕西省', city: '西安市', county: '长安区', level: 5, scene: 5 },
  { id: 41,  name: '南天门', high: 2665, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 42,  name: '跑马梁', high: 2660, province: '陕西省', city: '西安市', county: '鄠邑区', level: 5, scene: 4 },
  { id: 43,  name: '草链岭', high: 2646, province: '陕西省', city: '渭南市', county: '华州区', level: 5, scene: 3 },
  { id: 44,  name: '四方台', high: 2640, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 45,  name: '狗爬梁', high: 2640, province: '陕西省', city: '安康市', county: '宁陕县' },
  { id: 46,  name: '四咀山', high: 2633, province: '陕西省', city: '宝鸡市', county: '眉县' },
  { id: 47,  name: '朝天场', high: 2630, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 48,  name: '终南山', high: 2604, province: '陕西省', city: '商洛市', county: '柞水县', level: 5, scene: 3 },
  { id: 49,  name: '木王山', high: 2602, province: '陕西省', city: '商洛市', county: '镇安县' },
  { id: 50,  name: '三十担银梁', high: 2589, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 51,  name: '王喔咀', high: 2573, province: '陕西省', city: '西安市', county: '鄠邑区', level: 5, scene: 2 },
  { id: 52,  name: '高山草甸', high: 2550, province: '陕西省', city: '西安市', county: '长安区', level: 3, scene: 4 },
  { id: 53,  name: '鹞子梁', high: 2548, province: '陕西省', city: '汉中市', county: '佛坪县' },
  { id: 54,  name: '冻山', high: 2546, province: '陕西省', city: '宝鸡市', county: '太白县', level: 3, scene: 3 },
  { id: 55,  name: '老牛山', high: 2530, province: '陕西省', city: '渭南市', county: '华州区' },
  { id: 56,  name: '西牛背梁', high: 2521, province: '陕西省', city: '商洛市', county: '柞水县' },
  { id: 57,  name: '北草坡', high: 2501, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 58,  name: '刘秀寨', high: 2491, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 59,  name: '箭峪岭', high: 2449, province: '陕西省', city: '渭南市', county: '临渭区', level: 3, scene: 2 },
  { id: 60,  name: '金华山', high: 2416, province: '陕西省', city: '渭南市', county: '华州区' },
  { id: 61,  name: '铁板峰', high: 2380, province: '陕西省', city: '安康市', county: '宁陕县' },
  { id: 62,  name: '莲花山', high: 2358, province: '陕西省', city: '宝鸡市', county: '凤县' },
  { id: 63,  name: '南羊山', high: 2358, province: '陕西省', city: '安康市', county: '旬阳县' },
  { id: 64,  name: '光头山', high: 2355, province: '陕西省', city: '商洛市', county: '柞水县' },
  { id: 65, name: '太兴山', high: 2340, province: '陕西省', city: '西安市', county: '长安区', level: 3, scene: 4 },
  { id: 66,  name: '北川草甸', high: 2301, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 67,  name: '朝阳洞', high: 2300, province: '陕西省', city: '西安市', county: '鄠邑区' },
  { id: 68,  name: '终杆梁', high: 2280, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 69,  name: '源头岭', high: 2265, province: '陕西省', city: '渭南市', county: '华阴县' },
  { id: 70,  name: '窟窿山', high: 2261, province: '陕西省', city: '渭南市', county: '华州区' },
  { id: 71,  name: '西老君岭', high: 2253, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 72,  name: '青峰山', high: 2242, province: '陕西省', city: '宝鸡市', county: '陈仓区' },
  { id: 73,  name: '云台山', high: 2240, province: '陕西省', city: '西安市', county: '蓝田县', level: 3, scene: 4 },
  { id: 74,  name: '紫云山', high: 2197, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 75,  name: '黄草坪', high: 2192, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 76,  name: '将军帽', high: 2190, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 77,  name: '鸡头冠', high: 2181, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 78,  name: '天台山', high: 2172, province: '陕西省', city: '宝鸡市', county: '渭滨区' },
  { id: 79, name: '神仙岭', high: 2170, province: '陕西省', city: '宝鸡市', county: '眉县' },
  { id: 80,  name: '赛华山', high: 2166, province: '陕西省', city: '渭南市', county: '华阴县' },
  { id: 81,  name: '九华山', high: 2160, province: '陕西省', city: '商洛市', county: '柞水县' },
  { id: 82,  name: '石榴山', high: 2160, province: '陕西省', city: '宝鸡市', county: '岐山县' },
  { id: 83,  name: '华山', high: 2154, province: '陕西省', city: '渭南市', county: '华阴县' },
  { id: 84,  name: '石塔山', high: 2144, province: '陕西省', city: '宝鸡市', county: '陈仓区' },
  { id: 85,  name: '翠华山', high: 2132, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 86,  name: '东观音山', high: 2116, province: '陕西省', city: '西安市', county: '长安区', level: 3, scene: 4 },
  { id: 87,  name: '华阳草甸', high: 2100, province: '陕西省', city: '渭南市', county: '华阴县' },
  { id: 88,  name: '东大顶', high: 2097, province: '陕西省', city: '商洛市', county: '柞水县' },
  { id: 89,  name: '秦王山', high: 2090, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 90,  name: '宋家山', high: 2065, province: '陕西省', city: '宝鸡市', county: '渭滨区' },
  { id: 91,  name: '广洞山', high: 2063, province: '陕西省', city: '商洛市', county: '镇安县' },
  { id: 92,  name: '三齿炉', high: 2049, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 93,  name: '溜石板梁', high: 2038, province: '陕西省', city: '汉中市', county: '汉台区' },
  { id: 94,  name: '青岗坪', high: 2019, province: '陕西省', city: '汉中市', county: '汉台区' },
  { id: 95,  name: '鸡峰山', high: 2014, province: '陕西省', city: '宝鸡市', county: '渭滨区' },
  { id: 96,  name: '黄草坡', high: 2013, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 97,  name: '寨子顶', high: 2008, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 98,  name: '三公山', high: 2001, province: '陕西省', city: '渭南市', county: '华阴县' },
  { id: 99,  name: '九鼎万花山', high: 2000, province: '陕西省', city: '西安市', county: '长安区', level: 3, scene: 3 },
  { id: 100,  name: '佛山', high: 1988, province: '陕西省', city: '商洛市', county: '洛南县' },
  { id: 101,  name: '西观音山', high: 1985, province: '陕西省', city: '西安市', county: '周至县', level: 4, scene: 3 },
  { id: 102,  name: '凤凰山', high: 1984, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 103,  name: '库峪草甸', high: 1974, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 104,  name: '黑沟梁', high: 1968, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 105,  name: '天宝山', high: 1956, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 106,  name: '翠矶山', high: 1932, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 107,  name: '北羊山', high: 1920, province: '陕西省', city: '商洛市', county: '镇安县' },
  { id: 108,  name: '太平万花山', high: 1917, province: '陕西省', city: '西安市', county: '鄠邑区' },
  { id: 109,  name: '西楼山', high: 1911, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 110,  name: '闵家山', high: 1901, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 111,  name: '宝灯山', high: 1901, province: '陕西省', city: '商洛市', county: '柞水县' },
  { id: 112,  name: '雪瓦山', high: 1900, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 113,  name: '观音梁', high: 1895, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 114,  name: '黑虎咀', high: 1874, province: '陕西省', city: '西安市', county: '鄠邑区' },
  { id: 115,  name: '苜蓿山', high: 1868, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 116,  name: '冰凌顶', high: 1858, province: '陕西省', city: '渭南市', county: '华州区' },
  { id: 117,  name: '连云栈道', high: 1843, province: '陕西省', city: '宝鸡市', county: '凤县' },
  { id: 118,  name: '紫龙山', high: 1841, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 119,  name: '峪岭', high: 1841, province: '陕西省', city: '渭南市', county: '华阴县' },
  { id: 120,  name: '朝阳洞', high: 1839, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 121,  name: '龙华山', high: 1836, province: '陕西省', city: '宝鸡市', county: '太白县' },
  { id: 122,  name: '火龙关草甸', high: 1831, province: '陕西省', city: '商洛市', county: '洛南县' },
  { id: 123,  name: '凤凰山', high: 1821, province: '陕西省', city: '西安市', county: '鄠邑区' },
  { id: 124,  name: '冲天炮', high: 1817, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 125,  name: '嘉午台', high: 1810, province: '陕西省', city: '西安市', county: '长安区', level: 3, scene: 5 },
  { id: 126,  name: '佛头崖', high: 1806, province: '陕西省', city: '渭南市', county: '潼关县' },
  { id: 127,  name: '高尖山', high: 1791, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 128,  name: '九台山', high: 1791, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 129,  name: '人头山', high: 1779, province: '陕西省', city: '西安市', county: '长安区', level: 2, scene: 3 },
  { id: 130,  name: '云台山', high: 1776, province: '陕西省', city: '宝鸡市', county: '陈仓区' },
  { id: 131,  name: '翠峰山', high: 1773, province: '陕西省', city: '西安市', county: '周至县' },
  { id: 132,  name: '云蒙山', high: 1767, province: '陕西省', city: '商洛市', county: '洛南县' },
  { id: 133,  name: '九华山', high: 1766, province: '陕西省', city: '西安市', county: '鄠邑区', level: 3, scene: 4 },
  { id: 134,  name: '莲花洞', high: 1743, province: '陕西省', city: '西安市', county: '长安区' },
  { id: 135,  name: '风雨山', high: 1738, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 136,  name: '关路岭', high: 1733, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 138,  name: '磨沟岭', high: 1725, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 139,  name: '龙脉站', high: 1720, province: '陕西省', city: '渭南市', county: '潼关县' },
  { id: 140,  name: '文显山', high: 1709, province: '陕西省', city: '商洛市', county: '洛南县' },
  { id: 141,  name: '流峪草甸', high: 1700, province: '陕西省', city: '西安市', county: '蓝田县' },
  { id: 142,  name: '老君山', high: 1700, province: '陕西省', city: '商洛市', county: '洛南县' },
  { id: 143,  name: '终灵山', high: 1695, province: '陕西省', city: '西安市', county: '鄠邑区' },
  { id: 144,  name: '王道岭', high: 1691, province: '陕西省', city: '渭南市', county: '华阴县' },
  { id: 145,  name: '南五台', high: 1688, province: '陕西省', city: '西安市', county: '长安区', level: 3, scene: 5 },
  { id: 146,  name: '玉皇顶', high: 1684, province: '陕西省', city: '商洛市', county: '商州区' },
  { id: 147,  name: '中梁寨', high: 1679, province: '陕西省', city: '商洛市', county: '镇安县' },
  { id: 148,  name: '珍珠山', high: 1674, province: '陕西省', city: '汉中市', county: '城固县' },
  { id: 149,  name: '少华五峰', high: 1664, province: '陕西省', city: '渭南市', county: '华州区' },
  { id: 150,  name: '牛头山', high: 1662, province: '陕西省', city: '汉中市', county: '勉县' },
  { id: 151,  name: '圭峰山', high: 1505, province: '陕西省', city: '西安市', county: '鄠邑区', level: 3, scene: 4 },
];
