//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, Default)]
#[sea_orm(table_name = "caches")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    #[serde(rename(deserialize = "id", serialize = "id"))]
    pub id: i64,
    #[serde(rename(deserialize = "cacheKey", serialize = "cacheKey"))]
    pub cache_key: String,
    #[serde(rename(deserialize = "cacheValue", serialize = "cacheValue"))]
    pub cache_value: String,
    #[serde(rename(deserialize = "scope", serialize = "scope"))]
    pub scope: String,
    #[serde(rename(deserialize = "createdAt", serialize = "createdAt"))]
    pub created_at: DateTime,
    #[serde(rename(deserialize = "expiredAt", serialize = "expiredAt"))]
    pub expired_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
}
