//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, Default)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    #[serde(rename(deserialize = "catId", serialize = "catId"))]
    pub cat_id: i64,
    #[serde(rename(deserialize = "catVid", serialize = "catVid"))]
    pub cat_vid: String,
    #[serde(rename(deserialize = "catPid", serialize = "catPid"))]
    pub cat_pid: i64,
    #[serde(rename(deserialize = "catName", serialize = "catName"))]
    pub cat_name: String,
    #[serde(rename(deserialize = "catDesc", serialize = "catDesc"))]
    pub cat_desc: String,
    #[serde(rename(deserialize = "catDescFormat", serialize = "catDescFormat"))]
    pub cat_desc_format: String,
    pub weight: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::node_categories_map::Entity")]
    NodeCategory,
}

impl Related<super::node::Entity> for Entity {
    fn to() -> RelationDef {
        super::node_categories_map::Relation::Node.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::node_categories_map::Relation::Category.def().rev())
    }
}

impl Related<super::node_categories_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NodeCategory.def()
    }
}

