//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, Default)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub cat_id: i64,
    pub cat_vid: String,
    pub cat_pid: i64,
    pub cat_name: String,
    pub cat_desc: String,
    pub cat_desc_format: String,
    pub weight: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::node::Entity> for Entity {
    fn to() -> RelationDef {
        super::node_categories_map::Relation::Node.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::node_categories_map::Relation::Category.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
