//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comment_body")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub comment_id: i64,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub body_format: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
