//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, Default)]
#[sea_orm(table_name = "node_categories_map")]
pub struct Model {
    pub bundle: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub nid: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub cat_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::node::Entity",
        from = "Column::Nid",
        to = "super::node::Column::Nid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Node,
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::CatId",
        to = "super::category::Column::CatId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Category,
}

impl ActiveModelBehavior for ActiveModel {}
