//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, Default)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub nid: i64,
    pub uuid: String,
    pub vid: String,
    pub bundle: String,
    pub title: String,
    pub viewed: i32,
    pub deleted: String,
    #[serde(rename(deserialize = "publishedAt", serialize = "publishedAt"))]
    pub published_at: Option<DateTime>,
    #[serde(rename(deserialize = "createdBy", serialize = "createdBy"))]
    pub created_by: i64,
    #[serde(rename(deserialize = "updatedBy", serialize = "updatedBy"))]
    pub updated_by: i64,
    #[serde(rename(deserialize = "createdAt", serialize = "createdAt"))]
    pub created_at: DateTime,
    #[serde(rename(deserialize = "updatedAt", serialize = "updatedAt"))]
    pub updated_at: Option<DateTime>,
    #[serde(rename(deserialize = "deletedAt", serialize = "deletedAt"))]
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::node_body::Entity")]
    NodeBody,
}

impl Related<super::node_body::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NodeBody.def()
    }
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        super::node_categories_map::Relation::Category.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::node_categories_map::Relation::Node.def().rev())
    }
}


impl From<&str> for Column {
    fn from(name: &str) -> Self {
        match name {
            "created_at" => Column::CreatedAt,
            _ => Column::Nid,
        }
    }
}

