//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, Default)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub tag_id: i64,
    #[serde(rename(deserialize = "tagVid", serialize = "tagVid"))]
    pub tag_vid: String,
    #[serde(rename(deserialize = "tagName", serialize = "tagName"))]
    pub tag_name: String,
    pub weight: i32,
    #[serde(rename(deserialize = "tagCount", serialize = "tagCount"))]
    pub tag_count: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
