//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub uid: i64,
    pub uuid: String,
    pub username: String,
    pub nickname: String,
    pub password: String,
    pub salt: String,
    pub api_key: String,
    pub reset_token: String,
    pub reset_sent_at: Option<DateTimeUtc>,
    pub email_verify_token: String,
    pub email_verify_sent_at: Option<DateTimeUtc>,
    pub email_verified_at: Option<DateTimeUtc>,
    pub status: String,
    pub email: String,
    pub gender: String,
    pub avatar: String,
    pub role_id: i64,
    pub dpt_id: i64,
    pub remark: String,
    pub is_admin: String,
    pub phone: String,
    pub last_login_ip: String,
    pub last_login_at: Option<DateTimeUtc>,
    pub created_by: i64,
    pub updated_by: i64,
    pub created_at: DateTimeUtc,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
