import type { ToolItem } from './types';
 
export const STATIC_SITES: ToolItem[] = [
  {
    name: 'Next.js',
    url: 'https://nextjs.org/',
    description: '用于 SSG/SSR 的 React 框架，性能与 SEO 优秀，Vercel 集成完善。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Hugo',
    url: 'https://gohugo.io/',
    description: '超快的静态站点生成器，支持主题、i18n 与多种输出格式。',
    language: 'Go',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Gatsby',
    url: 'https://www.gatsbyjs.com/',
    description: '基于 React 与 GraphQL，插件生态丰富，适合快速构建可扩展站点。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Jekyll',
    url: 'https://jekyllrb.com/',
    description: '资深 SSG，将 Markdown/Liquid 渲染为静态站点；常用于 GitHub Pages。',
    language: 'Ruby',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: '11ty',
    url: 'https://www.11ty.dev/',
    description: '简洁灵活的 JavaScript SSG，支持多模板语言，开销极低。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Gridsome',
    url: 'https://gridsome.org/',
    description: '基于 Vue 的 SSG，生成静态 HTML 并在浏览器内重水化，内置 GraphQL 数据层。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Nuxt.js',
    url: 'https://nuxtjs.org/',
    description: 'Vue 框架，支持 SSR/SSG，模块化架构，SEO 友好。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Pelican',
    url: 'https://getpelican.com/',
    description: 'Python SSG，适合博客/个人站点，支持导入、主题与多语言。',
    language: 'Python',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Create React App',
    url: 'https://create-react-app.dev/',
    description: 'React 应用脚手架；虽非纯 SSG，但适合学习与简单静态部署。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Docusaurus',
    url: 'https://docusaurus.io/',
    description: '基于 React 的文档型 SSG，内置版本管理、搜索与国际化。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Slate',
    url: 'https://github.com/slatedocs/slate',
    description: '清爽的单页 API 文档生成器，灵感来自 Stripe/PayPal。',
    language: 'Ruby',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'MkDocs',
    url: 'https://www.mkdocs.org/',
    description: 'Python 文档型 SSG，使用 Markdown 与 YAML 配置，开箱即用。',
    language: 'Python',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Astro',
    url: 'https://astro.build/',
    description: '现代静态网站生成工具，支持岛屿架构，兼容多前端框架。',
    language: 'TypeScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Hexo',
    url: 'https://hexo.io/',
    description: 'Node.js 驱动的快速、简洁且高效的博客框架，秒级生成静态网页。',
    language: 'JavaScript/TypeScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Docsify',
    url: 'https://docsify.js.org/',
    description: '无需构建的文档网站生成器，按需加载 Markdown 即时渲染。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'VuePress',
    url: 'https://vuepress.vuejs.org/',
    description: '基于 Vue 的静态站点生成器，开箱即用的文档站点方案。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Zola',
    url: 'https://www.getzola.org/',
    description: 'Rust 编写的快速静态站点生成器，单个二进制文件即可运行。',
    language: 'Rust',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Umi',
    url: 'https://umijs.org/',
    description: '插件化的企业级前端框架，支持静态导出与服务端渲染。',
    language: 'TypeScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Nextra',
    url: 'https://nextra.site/',
    description: '简洁、强大且灵活的站点生成框架，基于 Next.js 与 MDX。',
    language: 'TypeScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'React Static',
    url: 'https://github.com/react-static/react-static',
    description: '面向 React 的渐进式静态站点生成器。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Middleman',
    url: 'https://middlemanapp.com/',
    description: 'Ruby 生态的静态站点生成器，适合定制化前端开发。',
    language: 'Ruby',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Hakyll',
    url: 'https://jaspervdj.be/hakyll/',
    description: 'Haskell 编写的静态网站编译库，灵活可编程。',
    language: 'Haskell',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Lume',
    url: 'https://lume.land/',
    description: '面向 Deno 的静态站点生成器，TypeScript 优先。',
    language: 'TypeScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Publish',
    url: 'https://github.com/JohnSundell/Publish',
    description: '面向 Swift 开发者的静态站点生成器。',
    language: 'Swift',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Harp',
    url: 'http://harpjs.com/',
    description: '静态 Web 服务器 / 生成器 / 打包器。',
    language: 'JavaScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Abell',
    url: 'https://abelljs.org/',
    description: '低门槛、框架无关且高度灵活的静态站点生成器，学习曲线平缓。',
    language: 'TypeScript',
    logo: '',
    category: 'static-site-generator',
  },
  {
    name: 'Fumadocs',
    url: 'https://github.com/fuma-nama/fumadocs',
    description: '优雅且灵活的 React 文档框架，基于 Next.js 应用路由。',
    language: 'TypeScript',
    logo: '',
    category: 'static-site-generator',
  },
];