[package]
name = "oicnp_cmd"
version = "0.0.1"
authors = ["Aqrun <aqrun@sina.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oicnp_core = { path = "../oicnp-core" }
oicnp_api = { path = "../oicnp-api" }
tokio = { version = "^1", features = ["macros", "rt-multi-thread"] }
dotenv = "^0"
lazy_static = "^1"
slab = "^0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
serde_yaml = "^0"
bson2 = "^2"
rbson = "^2"
log = "^0"
fast_log = { version = "^1", features = ["lz4", "zip", "gzip"]}
chrono = { version = "^0", features = ["serde"] }
tracing-subscriber = "^0"
regex = "^1"
gray_matter = "^0"
strum = "^0"
strum_macros = "^0"
rand = "^0"
rs-snowflake = "^0"
scru128 = "^2"
anyhow = "^1"
clap = { version = "^4", features = ["derive"] }

[dependencies.sea-orm]
version = "^0"
default-features = false
features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"]
