import type { ToolItem } from './types';

/**
 * 常用 AI 应用与助手
 */
export const AI_APPS_ITEMS: ToolItem[] = [
  {
    name: 'ChatGPT',
    url: 'https://chat.openai.com/',
    description: 'OpenAI 的通用对话与创作助手，支持多模态与广泛插件生态。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Claude',
    url: 'https://claude.ai/',
    description: 'Anthropic 推出的安全友好型助理，长文本与工具使用能力强。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Gemini',
    url: 'https://gemini.google.com/',
    description: 'Google 的多模态助手，整合搜索、文档与工作流生态。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Copilot',
    url: 'https://github.com/features/copilot',
    description: 'GitHub 与 OpenAI 合作打造的编程助理，支持 IDE 内联补全与聊天。',
    language: 'TypeScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Cursor',
    url: 'https://www.cursor.com/',
    description: '面向工程师的 AI IDE，强化代码意图理解、改写与多文件协作。',
    language: 'TypeScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: '豆包（Doubao）',
    url: 'https://www.doubao.com/',
    description: '字节跳动旗下 AI 助手，覆盖创作、办公与企业应用场景。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: '腾讯元宝',
    url: 'https://yuanbao.tencent.com/',
    description: '腾讯推出的大模型助手，支持对话、写作、图像与企业集成。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Meta AI',
    url: 'https://ai.meta.com/meta-ai/',
    description: 'Meta 的 AI 助手，融入社交与多媒体体验，支持生成式功能。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Perplexity',
    url: 'https://www.perplexity.ai/',
    description: '以检索增强为核心的回答与研究助手，提供引用与深入探索。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Poe',
    url: 'https://poe.com/',
    description: '聚合多模型的对话平台，快速切换与分享机器人配置。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Notion AI',
    url: 'https://www.notion.so/product/ai',
    description: '嵌入 Notion 的写作与整理助手，提升笔记、文档与知识库效率。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Midjourney',
    url: 'https://www.midjourney.com/',
    description: '高质量图像生成工具，擅长艺术风格与创意视觉表达。',
    language: 'JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Stable Diffusion (WebUI)',
    url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    description: '开源图像生成生态，丰富的模型与插件，私有化部署灵活。',
    language: 'Python',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: 'Kimi',
    url: 'https://kimi.moonshot.cn/',
    description: 'Moonshot 推出的中文长文档助手，支持复杂阅读与问答任务。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
  {
    name: '通义千问（Qwen）',
    url: 'https://qwen.ai/',
    description: '阿里云大模型应用与生态，覆盖 Agent、代码、图像与多模态。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'ai-apps',
  },
];

