import type { ToolItem } from './types';

/**
 * Markdown / MDX 相关生态
 */
export const MARKDOWN_MDX_ITEMS: ToolItem[] = [
  {
    name: 'MDX',
    url: 'https://mdxjs.com/',
    description: '将 Markdown 与 JSX 结合，内容与组件共存，适合文档与内容站点。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'remark',
    url: 'https://remark.js.org/',
    description: '基于 unified 的 Markdown 处理器，插件体系成熟，支持多种转换。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'rehype',
    url: 'https://rehypejs.org/',
    description: 'HTML 处理器（unified 家族），常与 remark 配合实现 Markdown→HTML 流程。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'unified',
    url: 'https://unifiedjs.com/',
    description: '语法树处理生态的核心框架，串联 remark/rehype 等处理流程。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'contentlayer',
    url: 'https://www.contentlayer.dev/',
    description: '内容类型化与生成工具，结合 Next.js/MDX 提供类型安全的数据层。',
    language: 'TypeScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'next-mdx-remote',
    url: 'https://github.com/hashicorp/next-mdx-remote',
    description: '在 Next.js 中远程/动态渲染 MDX 内容的解决方案。',
    language: 'TypeScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'gray-matter',
    url: 'https://github.com/jonschlinkert/gray-matter',
    description: '解析 Markdown Front Matter（YAML/TOML/JSON），常用于内容站点。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'markdown-it',
    url: 'https://github.com/markdown-it/markdown-it',
    description: '可扩展的 Markdown 解析器，速度快、兼容性好、插件丰富。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  // remark 插件
  {
    name: 'remark-gfm',
    url: 'https://github.com/remarkjs/remark-gfm',
    description: '支持 GitHub Flavored Markdown（表格、删除线、任务列表等）。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'remark-breaks',
    url: 'https://github.com/remarkjs/remark-breaks',
    description: '将换行符转换为 <br>，匹配 GFM 的换行行为。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'remark-slug',
    url: 'https://github.com/remarkjs/remark-slug',
    description: '为标题自动生成锚点 id，便于目录与跳转。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'remark-autolink-headings',
    url: 'https://github.com/remarkjs/remark-autolink-headings',
    description: '为标题自动插入锚点链接，便于复制与分享。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'remark-toc',
    url: 'https://github.com/remarkjs/remark-toc',
    description: '根据文档标题自动生成目录（Table of Contents）。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'remark-emoji',
    url: 'https://github.com/rhysd/remark-emoji',
    description: '将 :smile: 等短码转换为 emoji（支持多种渲染方式）。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  // rehype 插件
  {
    name: 'rehype-highlight',
    url: 'https://github.com/rehypejs/rehype-highlight',
    description: '基于 highlight.js 的代码高亮，零配置快速上手。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'rehype-pretty-code',
    url: 'https://github.com/atomiks/rehype-pretty-code',
    description: '结合 shiki 实现漂亮的代码高亮，支持行高亮与注释。',
    language: 'TypeScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'rehype-slug',
    url: 'https://github.com/rehypejs/rehype-slug',
    description: '为 HTML 标题元素生成 id，方便目录与跳转。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'rehype-autolink-headings',
    url: 'https://github.com/rehypejs/rehype-autolink-headings',
    description: '为 HTML 标题自动插入可点击的锚点链接。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'rehype-raw',
    url: 'https://github.com/rehypejs/rehype-raw',
    description: '在 rehype 中安全地解析并合并原始 HTML（与 remark-rehype 配合）。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  // unified/转换链相关
  {
    name: 'remark-rehype',
    url: 'https://github.com/remarkjs/remark-rehype',
    description: '将 Markdown AST（mdast）转换为 HTML AST（hast）。',
    language: 'TypeScript/JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
  {
    name: 'rehype-stringify',
    url: 'https://github.com/rehypejs/rehype/tree/main/packages/rehype-stringify',
    description: '将 HTML AST（hast）序列化为字符串 HTML。',
    language: 'JavaScript',
    logo: '',
    category: 'markdown-mdx',
  },
];

